export const astroDictEn: Record<string, string> = {
  // Elements
  'Mộc': 'Wood',
  'Hỏa': 'Fire',
  'Thổ': 'Earth',
  'Kim': 'Metal',
  'Thủy': 'Water',
  
  // Heavenly Stems
  'Giáp': 'Jia (Yang Wood)',
  'Ất': 'Yi (Yin Wood)',
  'Bính': 'Bing (Yang Fire)',
  'Đinh': 'Ding (Yin Fire)',
  'Mậu': 'Wu (Yang Earth)',
  'Kỷ': 'Ji (Yin Earth)',
  'Canh': 'Geng (Yang Metal)',
  'Tân': 'Xin (Yin Metal)',
  'Nhâm': 'Ren (Yang Water)',
  'Quý': 'Gui (Yin Water)',

  // Earthly Branches
  'Tý': 'Zi (Rat)',
  'Sửu': 'Chou (Ox)',
  'Dần': 'Yin (Tiger)',
  'Mão': 'Mao (Rabbit)',
  'Thìn': 'Chen (Dragon)',
  'Tỵ': 'Si (Snake)',
  'Ngọ': 'Wu (Horse)',
  'Mùi': 'Wei (Goat)',
  'Thân': 'Shen (Monkey)',
  'Dậu': 'You (Rooster)',
  'Tuất': 'Xu (Dog)',
  'Hợi': 'Hai (Pig)',
  
  // Ten Gods
  'Tỷ': 'Friend',
  'Kiếp': 'Rob Wealth',
  'Thực': 'Eating God',
  'Thương': 'Hurting Officer',
  'T.Tài': 'Direct Wealth',
  'C.Tài': 'Indirect Wealth',
  'Sát': 'Seven Killings',
  'Quan': 'Direct Officer',
  'Kiêu': 'Indirect Resource',
  'Ấn': 'Direct Resource',

  // Hexagrams / Trigrams components
  'Càn': 'Qian (Heaven)',
  'Khảm': 'Kan (Water)',
  'Cấn': 'Gen (Mountain)',
  'Chấn': 'Zhen (Thunder)',
  'Tốn': 'Xun (Wind)',
  'Ly': 'Li (Fire)',
  'Khôn': 'Kun (Earth)',
  'Đoài': 'Dui (Lake)',

  // Gieo que components
  'Thế': 'Subject',
  'Ứng': 'Object',
  'Hào': 'Line',
  'Động': 'Moving',
  'Quẻ Chủ': 'Original Hexagram',
  'Quẻ Biến': 'Transformed Hexagram',
  'Quẻ Hổ': 'Nuclear Hexagram',
  'Ý Nghĩa': 'Meaning',
  'Thiên Khắc Địa Xung': 'Heavenly Clash & Earthly Clash',
  'Thiên Hợp Địa Hợp': 'Heavenly Match & Earthly Match',
  
  // Common terms
  'Nam': 'Male',
  'Nữ': 'Female',
  'Dương Lịch': 'Solar',
  'Âm Lịch': 'Lunar',
  'Ngày': 'Day',
  'Tháng': 'Month',
  'Năm': 'Year',
  'Giờ': 'Hour',
  'Trụ': 'Pillar',
  
  // Tu Vi specific terms
  'Mệnh': 'Destiny',
  'Tài Bạch': 'Wealth',
  'Huynh Đệ': 'Brothers',
  'Điền Trạch': 'Property',
  'Quan Lộc': 'Career',
  'Nô Bộc': 'Servants',
  'Thiên Di': 'Travel',
  'Tật Ách': 'Health',
  'Phu Thê': 'Spouse',
  'Tử Tức': 'Children',
  'Phúc Đức': 'Karma',
  'Phụ Mẫu': 'Parents',
  'Thân Mệnh': 'Body',

  // Additional elements
  'Đại Vận': 'Luck Cycles (Da Yun)',
  'Tiểu Vận': 'Minor Cycles',
  'Thái Nguyên': 'Conception Pillar',
  'Mệnh Cung': 'Life House',
  'Năm Không': 'Year Emptiness',
  'Ngày Không': 'Day Emptiness',
  'Thập Thần': 'Ten Gods',
  'Can': 'Stem',
  'Chi': 'Branch',
  'Tàng Can': 'Hidden Stems',
  'Quy Luật': 'Pattern Rules',
  'Trang trí': 'Decor',
  'Luận Giải AI Tứ Trụ': 'Bazi AI Analysis',
  'Phân Tích Quẻ': 'Hexagram Analysis',
  'Lục Hào Phệ khuyết': 'Six-Line Hexagram',
  
  // 12 Phases
  'Trường sinh': 'Birth',
  'Mộc dục': 'Bath',
  'Quan đới': 'Youth',
  'Lâm quan': 'Prospering',
  'Đế vượng': 'Peak',
  'Suy': 'Weakening',
  'Bệnh': 'Sick',
  'Tử': 'Death',
  'Mộ': 'Grave',
  'Tuyệt': 'Extinction',
  'Thai': 'Conception',
  'Dưỡng': 'Gestating',
  
  // NaYin Elements
  'Hải Trung Kim': 'Sea Metal',
  'Lư Trung Hỏa': 'Furnace Fire',
  'Đại Lâm Mộc': 'Forest Wood',
  'Lộ Bàng Thổ': 'Roadside Earth',
  'Kiếm Phong Kim': 'Sword Metal',
  'Sơn Đầu Hỏa': 'Mountain Top Fire',
  'Giản Hạ Thủy': 'Stream Water',
  'Thành Đầu Thổ': 'Wall Earth',
  'Bạch Lạp Kim': 'White Wax Metal',
  'Dương Liễu Mộc': 'Willow Wood',
  'Tuyền Trung Thủy': 'Spring Water',
  'Ốc Thượng Thổ': 'Roof Earth',
  'Tích Lịch Hỏa': 'Lightning Fire',
  'Tùng Bách Mộc': 'Cedar Wood',
  'Trường Lưu Thủy': 'Long Flowing Water',
  'Sa Trung Kim': 'Sand Metal',
  'Sơn Hạ Hỏa': 'Mountain Foot Fire',
  'Bình Địa Mộc': 'Plains Wood',
  'Bích Thượng Thổ': 'Wall Earth',
  'Kim Bạch Kim': 'Gold Foil Metal',
  'Phúc Đăng Hỏa': 'Lamp Fire',
  'Thiên Hà Thủy': 'Sky River Water',
  'Đại Dịch Thổ': 'Large River Earth',
  'Thoa Xuyến Kim': 'Hairpin Metal',
  'Tang Đố Mộc': 'Mulberry Wood',
  'Đại Khê Thủy': 'Great Stream Water',
  'Sa Trung Thổ': 'Sand Earth',
  'Thiên Thượng Hỏa': 'Heaven Fire',
  'Thạch Lựu Mộc': 'Pomegranate Wood',
  'Đại Hải Thủy': 'Ocean Water',
  
  // Symbolic Stars (Shen Sha)
  'Thiên Ất QN': 'Nobleman (Tian Yi)',
  'Niên Quý Nhân': 'Year Nobleman',
  'Thiên Đức': 'Heavenly Virtue',
  'Nguyệt Đức': 'Monthly Virtue',
  'Hoa Cái': 'Elegant Seal',
  'Đào Hoa': 'Peach Blossom',
  'Kiếp Sát': 'Robbing Devil',
  'Không Vong': 'Void (Xu Kong)',
  'Thái Tuế': 'Grand Duke (Tai Sui)',
  'Văn Xương': 'Academic Star',
  'Học Sỹ': 'Academician',
  'Lộc Thần': 'Prosperity Star',
  'Tuế Lộc': 'Year Prosperity',
  'Hồng Loan': 'Red Phoenix',
  'Cô Thần': 'Lonesome Star',
  'Quả Tú': 'Solitary Star',
  'Dịch Mã': 'Sky Horse',
  'Tướng Tinh': 'General Star',
  'Quan Phù': 'Officer Star',
};
