export const HEXAGRAM_MEANINGS: Record<string, string> = {
  "0,0": "Bát Thuần Càn: Cương kiện, mạnh mẽ, vạn sự hanh thông. Tượng trời sáng tạo, đấng quân tử tự cường không nghỉ.", 
  "0,1": "Thiên Trạch Lý: Dẫm lên, đi theo, cẩn thận khuôn phép. Tượng đi sau đuôi cọp nhưng không bị cắn.", 
  "0,2": "Thiên Hỏa Đồng Nhân: Cùng người hòa đồng, thân thiện, đồng tâm hiệp lực. Tượng mặt trời giữa trời sáng soi vạn vật.", 
  "0,3": "Thiên Lôi Vô Vọng: Không xảo trá, thuận theo tự nhiên, tránh vọng động làm bừa để khỏi mang họa.", 
  "0,4": "Thiên Phong Cấu: Gặp gỡ đột ngột, cơ duyên bất ngờ, phong trần. Tượng gió thổi quét qua dưới vòm trời.", 
  "0,5": "Thiên Thủy Tụng: Kiện tụng, tranh cãi, mâu thuẫn dai dẳng. Tượng trời và nước đi ngược chiều nhau.", 
  "0,6": "Thiên Sơn Độn: Rút lui, ẩn tránh, chờ thời, tránh xa phiền não khi tiểu nhân đang lộng hành.", 
  "0,7": "Thiên Địa Bĩ: Bế tắc, không thông, vận suy. Tượng trời đất không giao hòa, kẻ xấu nắm quyền.",

  "1,0": "Trạch Thiên Quải: Quyết đoán, dứt khoát, diệt trừ hung ác. Tượng nước hồ dâng ngập nghé trời, cương quyết tuôn chảy.", 
  "1,1": "Bát Thuần Đoài: Hân hoan, vui vẻ, hòa duyệt, lời nói êm tai. Tượng hai hồ nước nương tựa, cùng tưới tắm cho nhau.", 
  "1,2": "Trạch Hỏa Cách: Cải cách, thay đổi, bỏ cũ lập mới, lột xác. Tượng lửa làm cạn nước, nước dập tắt lửa.", 
  "1,3": "Trạch Lôi Tùy: Tùy thuận, theo nhau, tòng thuận. Tượng sấm giấu trong đầm tĩnh lặng, ứng biến theo hoàn cảnh.", 
  "1,4": "Trạch Phong Đại Quá: Quá mức, gánh nặng, làm quá sức. Tượng cây lớn đứng giữa gió lốc, cương quá ắt gãy.", 
  "1,5": "Trạch Thủy Khốn: Khốn đốn, cùng quẫn, nguy nan trùng trùng. Tượng mầm cây mọc trong đầm cạn khô.", 
  "1,6": "Trạch Sơn Hàm: Cảm ứng, rung động chớp nhoáng, yêu thương giao cảm. Tượng trai út gái út mến nhau.", 
  "1,7": "Trạch Địa Tụy: Nhóm họp, tụ tập, hội tụ quần anh, gom góp tinh hoa. Tượng nước tụ trên mặt đất thành hồ lớn.",

  "2,0": "Hỏa Thiên Đại Hữu: Của cải dồi dào, quyền bính, sở hữu lớn lao. Tượng mặt trời lên cao soi sáng bừng cõi thế.", 
  "2,1": "Hỏa Trạch Khuê: Trái ngược, chia lìa, bất hòa, mỗi người một nẻo. Tượng lửa bốc lên trên, hồ nước tụt xuống dưới.", 
  "2,2": "Bát Thuần Ly: Sáng sủa, rực rỡ, bám víu, nương tựa rực sáng. Tượng hai ngọn lửa nối tiếp nhau rực cháy.", 
  "2,3": "Hỏa Lôi Phệ Hạp: Cắn hợp, trừng trị, luật pháp cương quyết. Tượng sấm sét đi liền nhau, tiêu trừ kẻ ác.", 
  "2,4": "Hỏa Phong Đỉnh: Đúc kết, rèn luyện, chế độ mới, thăng tiến vinh quang. Tượng gió thổi lửa đun vạc, hóa cũ thành mới.", 
  "2,5": "Hỏa Thủy Vị Tế: Dở dang, chưa xong, cần cố gắng tiếp. Tượng lửa trên nước dưới không giao hòa, việc chưa thành.", 
  "2,6": "Hỏa Sơn Lữ: Khách lạ, đi xa, lang bạt, tạm vị. Tượng lửa cháy lan qua đỉnh núi, không ở đâu lâu bền.", 
  "2,7": "Hỏa Địa Tấn: Tiến lên, phát triển, rạng rỡ huy hoàng. Tượng ánh mặt trời ló rạng bắt đầu nhô lên khỏi măt đất.",

  "3,0": "Lôi Thiên Đại Tráng: Cực kỳ mạnh mẽ, thế lực ngút ngàn, cường liệt. Quẻ khuyên cương quyết nhưng chớ tự kiêu.", 
  "3,1": "Lôi Trạch Quy Muội: Không chính thức, bồng bột. Tượng gái trẻ đi lấy chồng do đam mê dục vọng mà lấn át nề nếp.", 
  "3,2": "Lôi Hỏa Phong: Cực kì vĩ đại, thịnh vượng, rực rỡ tột đỉnh. Tượng sấm sét sáng lòa nhưng điềm báo sắp tàn suy.", 
  "3,3": "Bát Thuần Chấn: Chấn động, sấm sét, nơm nớp sợ hãi rồi sẽ bình an. Báo hiệu sự biến chuyển và tỉnh thức.", 
  "3,4": "Lôi Phong Hằng: Lâu dài, bền bỉ, kiên nhẫn bám trụ. Tượng sấm gió đi cùng, đạo nghĩa vợ chồng keo sơn dài lâu.", 
  "3,5": "Lôi Thủy Giải: Giải thoát, tháo gỡ khó khăn, ân xá. Tượng mưa rào đổ dội, sấm sét tan bão táp, vạn vật hồi sinh.", 
  "3,6": "Lôi Sơn Tiểu Quá: Tiểu nhân quá đáng, cảnh giác nhỏ, làm việc nhỏ thì thành. Tượng chim bay đi bỏ lại tiếng kêu.", 
  "3,7": "Lôi Địa Dự: Do dự, tính trước, nhàn hạ hòa sướng. Tượng tiếng sấm đì đùng trong đất báo mùa Xuân sắp tới.",

  "4,0": "Phong Thiên Tiểu Súc: Súc tích nhỏ, tích lũy từ từ chưa đủ lượng. Tượng bóng mây bay ngất trời nhưng chưa đổ mưa.", 
  "4,1": "Phong Trạch Trung Phu: Thành tín, tin tưởng trung thực từ nội tâm. Tượng gió thổi trên mặt đầm gợn sóng cảm ứng.", 
  "4,2": "Phong Hỏa Gia Nhân: Người trong nhà, xây dựng luân lý gia đình, hậu phương vững chắc. Tượng gió tựa lửa bốc lên.", 
  "4,3": "Phong Lôi Ích: Làm ích lợi, giúp đỡ, phát triển cực nhanh. Tượng gió thổi sấm rền, thấy điều thiện phải làm ngay.", 
  "4,4": "Bát Thuần Tốn: Thuận theo, nhún nhường, quy phục. Tượng hai luồng gió đuổi theo nhau, len lỏi thâm nhập mọi nơi.", 
  "4,5": "Phong Thủy Hoán: Ly tán, hóa giải oán thù, linh động lách qua nguy hiểm. Tượng gió thổi mặt nước tan những lớp băng.", 
  "4,6": "Phong Sơn Tiệm: Tiến tới dần dần, chậm rãi mà chắc chắn. Tượng cây mọc trên sườn núi lớn lên từng ngày.", 
  "4,7": "Phong Địa Quan: Xem xét, quan sát đại cục, nêu gương sáng. Tượng cảnh gió thổi vi vu qua mặt đất không chừa chỗ nào.",

  "5,0": "Thủy Thiên Nhu: Chờ đợi thời cơ, nấn ná, hoãn lại. Tượng mây tụ nhưng chưa mưa, không nên hấp tấp.", 
  "5,1": "Thủy Trạch Tiết: Chừng mực, tiết chế, kìm hãm đam mê. Tượng nước trong đầm chứa có sức, tràn đầy là nguy.", 
  "5,2": "Thủy Hỏa Ký Tế: Đã hoàn tất, vạn sự thành tựu, chu toàn. Tượng nước ở trên đun nấu ngọn lửa ở dưới chín thức ăn.", 
  "5,3": "Thủy Lôi Truân: Mới sinh gian truân, khó nhọc lúc ban đầu. Tượng mầm lá nứt vỏ chui ra khỏi mặt đất sau cơn bão.", 
  "5,4": "Thủy Phong Tỉnh: Nguồn nước giếng, nền tảng, không thay đổi nguyên lý. Nuôi dưỡng vạn vật mà chẳng vụ danh lợi.", 
  "5,5": "Bát Thuần Khảm: Hiểm nguy, hố sâu, vất vả trùng trùng điệp điệp. Tượng hai dòng nước dữ cuộn vào nhau.", 
  "5,6": "Thủy Sơn Kiển: Trở ngại, bế tắc ngáng đường, chân đau khó bước. Tượng nước lũ bị núi tuyết chặn lại, tiến thoái lưỡng nan.", 
  "5,7": "Thủy Địa Tỷ: Gần gũi, kết hợp mật thiết, tương thân tương ái. Tượng nước thấm rịn vào lòng đất chan hòa.",

  "6,0": "Sơn Thiên Đại Súc: Chứa đựng lớn, tàng trữ, tài ba bao phủ bế quan đợi thời. Tượng ngọn núi trùm lấp cả bầu trời.", 
  "6,1": "Sơn Trạch Tổn: Suy tổn, bớt đi phần dưới để bù đắp phần trên, thu liễm. Tượng móc đất dưới đầm để vun đắp đỉnh núi.", 
  "6,2": "Sơn Hỏa Bí: Treo đồ trang sức, vẻ ngoài tô điểm đẹp đẽ, dối trá bên trong. Tượng ngọn lửa hắt lên ráng chiều quanh núi.", 
  "6,3": "Sơn Lôi Di: Sự nuôi dưỡng, cẩn trọng trong ẩm thực và ngôn từ. Tượng sấm ở dưới núi như quai hàm nhai mở ra khép lại.", 
  "6,4": "Sơn Phong Cổ: Sâu mọt, đổ nát, mục rỗng, bắt buộc phải canh tân chỉnh sửa. Tượng gió quanh quẩn góc núi thối mục.", 
  "6,5": "Sơn Thủy Mông: Mờ mịt, trẻ thơ ngu dốt, phải tìm thầy học đạo. Tượng mây sương giăng mờ mịt chân núi dốc.", 
  "6,6": "Bát Thuần Cấn: Dừng lại, đứng yên, ngăn trở, giữ vững tĩnh lặng bất biến. Tượng hai ngọn núi sừng sững trấn đóng.", 
  "6,7": "Sơn Địa Bác: Kẻ ác lấn át, tiêu mòn, lột bỏ, cơ nghiệp đến ngày sụp đổ. Tượng núi cao đã lở rơi xuống bình địa.",

  "7,0": "Địa Thiên Thái: Vạn vật giao hòa, thái bình, yên vui may mắn tột đỉnh. Tượng đất ở trên trời ở dưới, âm dương giao quyến.", 
  "7,1": "Địa Trạch Lâm: Bao lâm, bề trên soi xét kẻ dưới, lớn rộng. Tượng mặt đất phủ tràn trên miệng mặt đầm nước.", 
  "7,2": "Địa Hỏa Minh Di: Tăm tối, hại minh, tài năng bị dìm, tránh để lộ hào quang. Tượng ngọn lửa bị vùi tắt rụi dưới lòng đất.", 
  "7,3": "Địa Lôi Phục: Khôi phục, trở lại, mầm sống lóe sáng. Tượng mầm non mùa xuân bắt đầu nảy mầm sau lớp tuyết tan.", 
  "7,4": "Địa Phong Thăng: Thăng tiến, vươn cao, cất cánh đâm chồi ngoạn mục. Tượng cây cối vươn thẳng bay khỏi lòng đất dầy.", 
  "7,5": "Địa Thủy Sư: Đám đông, quần chúng, quân đội phải xuất tiết kỷ cương. Tượng nước ngầm tập hợp sức mạnh dưới đất rồng.", 
  "7,6": "Địa Sơn Khiêm: Khiêm nhường, lùi một bước, cáo quan tu ẩn. Tượng núi dẫu cao cũng nép chìm mình dưới đất mẹ.", 
  "7,7": "Bát Thuần Khôn: Nhu thuận, nhu mì, bao dung chở che. Tượng mặt đất nối mặt đất dung chứa muôn loài bất vi."
};
