export const STAR_MEANINGS: Record<string, string> = {
  // --- ĐẠI KIẾT TINH TỔNG HỢP ---
  'Sát Cống': 'Đại kiết tinh. Rất tốt cho mọi việc, có thể hoá giải được các sao xấu (chỉ trừ Kim thần thất sát).',
  'Trực Tinh': 'Đại kiết tinh. Tốt mọi việc, đặc biệt là cưới hỏi, chuyển nhà, có thể giải được sao xấu.',
  'Nhân Chuyên': 'Đại kiết tinh. Tốt mọi việc, giúp hóa giải các hung tinh, mang lại bình an.',
  'Thiên Đức': 'Kiết tinh. Vạn sự hanh thông, hóa giải hung sát, có cứu giải lớn.',
  'Nguyệt Đức': 'Kiết tinh. Tốt mọi việc, công danh lợi lộc thuận lợi, giải tai ách.',
  'Thiên Đức Hợp': 'Kiết tinh. Có sự phù trợ, tốt mọi việc, thiên địa hòa hợp.',
  'Nguyệt Đức Hợp': 'Kiết tinh. Tốt mọi việc, nhiều phú quý, an lành.',
  'Thiên Xá': 'Đại cát tinh. Tốt mọi việc, siêu độ, giải oan, tế lễ, phá ác.',

  // --- CÁC CÁT TINH PHỔ BIẾN ---
  'Thiên Ân': 'Cát tinh. Tốt cho mọi việc, mang ý nghĩa được ơn huệ của trời ban phước.',
  'Nguyệt Ân': 'Cát tinh. Tốt cho mọi việc, mang phúc lộc của tháng.',
  'Hoàng Ân': 'Cát tinh. Tốt cho việc nhận tiền tài, nhận chức tước, phong thưởng.',
  'Thiên Quý': 'Kiết tinh. Tốt mọi việc, công danh hanh thông.',
  'Thiên Hỉ': 'Cát tinh. Rất tốt cho giá thú (cưới hỏi), xuất hành, các việc mang tính vui vẻ.',
  'Thiên Y': 'Cát tinh. Đại cát cho việc tế tự, cầu y, chữa bệnh, giải nạn.',
  'Sinh Khí': 'Cát tinh. Tốt mọi việc, tốt nhất cho động thổ, làm nhà, trồng cây, tạo sinh khí mới.',
  'Phúc Đức': 'Cát tinh. Tốt cho mọi việc, đặc biệt là an táng, làm nhà, được phúc thần độ mạng.',
  'Ích Hậu': 'Cát tinh. Tốt mọi việc, đặc biệt giá thú (cưới xin) và cầu tài.',
  'Đại Hồng Sa': 'Cát tinh. Tốt cho mọi việc, mọi sự vạn cát.',
  'Lục Hợp': 'Cát tinh. Tốt mọi việc, có quý nhân tương trợ, đi làm gì cũng có người giúp.',
  'Tam Hợp': 'Cát tinh. Tốt mọi việc, chủ về sự hòa hợp, sự thuận lợi, kết nối vạn vật.',
  'Mẫu Thương': 'Cát tinh. Tốt cho cầu tài, khai trương, mở cửa hàng, nhà kho (kho báu của mẹ).',
  'Kim Đường': 'Cát tinh. Tốt mọi việc, đặc biệt xây dựng, động thổ.',
  'Ngọc Đường': 'Hoàng đạo kiết tinh. Tốt mọi việc, hanh thông, công danh vinh hiển, thi cử dễ đậu.',
  'Minh Đường': 'Hoàng đạo kiết tinh. Tốt mọi việc, khai trương, xuất hành đều làm ăn sáng sủa.',
  'Thanh Long': 'Hoàng đạo kiết tinh. Rất tốt cho mọi việc, đặc biệt hỷ sự, mang lại điềm lành lớn.',
  'Kim Quỹ': 'Hoàng đạo kiết tinh. Đại cát cho cưới hỏi, sinh đẻ, cầu tài giữ của.',
  'Tư Mệnh': 'Hoàng đạo kiết tinh. Tốt mọi việc, sự nghiệp vẻ vang, thăng chức.',
  'Thiên Mã': 'Cát tinh. Tốt cho xuất hành, giao dịch, thay đổi công việc, đi mưu sự.',
  'Dịch Mã': 'Cát tinh. Tốt cho sự thay đổi, chuyển nhà, đi xa, đổi việc.',
  'Giải Thần': 'Cát tinh. Có khả năng hóa giải nhiều sao xấu, giảm bớt hung họa, tốt cho tế tự tố tụng.',
  'Nguyệt Không': 'Cát tinh. Tốt làm nhà, sửa nhà, đặc biệt khi dựng cột, cất nóc.',
  'Thời Đức': 'Cát tinh. Tốt mọi việc, thuận lợi hợp thời.',
  'Thánh Tâm': 'Cát tinh. Tốt cho tế lễ, cầu phúc.',
  'Cát Kỳ': 'Cát tinh. Tốt mọi việc, đặc biệt khai trương, giao dịch, cầu tài.',
  'Thiên Quan': 'Kiết tinh. Cầu danh, cầu tài, gặp gỡ quý nhân đều tốt.',
  'Phúc Tinh': 'Kiết tinh. Cát tường, giảm tai họa, mang đến tài lộc nhỏ.',
  'Hỷ Thần': 'Kiết tinh. Thần mang lại điềm vui, tốt cho các việc lễ nghi tân hôn.',
  'Thiên Vu': 'Cát tinh. Tốt cho cầu tế, chiêm bốc, giải hạn.',
  'Phổ Hộ': 'Cát tinh. Tốt cho việc giúp người, chữa bệnh, tế tự.',
  'Tứ Tương': 'Cát tinh. Tốt mọi việc, thích hợp để tu tạo, động thổ.',
  'Dân Nhật': 'Cát tinh. Tốt mọi việc, có lợi cho công việc của dân thường.',
  'Dương Đức': 'Cát tinh. Tốt cho các sự việc dương minh, ban ngày.',
  'Tuế Đức': 'Cát tinh của năm. Tốt mọi việc, giảm nhẹ hung tin trong năm.',
  'Tuế Đức Hợp': 'Cát tinh. Tuế Đức kết hợp, chủ về đoàn kết, tụ hội.',
  'Thiên Nguyện': 'Cát tinh. Thích hợp cầu tự, làm việc phước đức.',
  'Nguyệt Kiến': 'Cát tinh (ở mức vừa phải). Tốt khi tiến hành sự việc có quy mô vừa.',
  'Nguyệt Tương': 'Cát tinh, giúp âm dương cân bằng, đem lại sự hỗ trợ.',
  'Tương Nhật': 'Cát tinh. Tốt cho mọi thứ.',
  'Vương Nhật': 'Cát tinh. Tốt cho xin việc, nhậm chức, yết kiến sếp.',
  'Thời Dương': 'Cát tinh. Rất tốt khi tiến hành vào ban ngày, có dương khí.',
  'Tục Thế': 'Cát tinh. Tốt cho giá thú, cầu con, sinh đẻ.',
  'Kính An': 'Cát tinh. Tốt cho sự dọn dẹp, an vị.',
  'Âm Đức': 'Cát tinh. Tốt cho việc làm từ thiện tĩnh lặng, táng lăng.',
  'Bảo Quang': 'Cát tinh. Tốt mọi việc, tài lộc dồi dào, tỏa sáng.',
  'Thiên Hậu': 'Cát tinh. Tốt cho hôn nhân, công việc của nữ giới.',
  'Phúc Sinh': 'Cát tinh. Tốt cho việc sinh nở, chăn nuôi, gieo giống.',
  'Ngũ Hợp': 'Cát tinh. Tốt mọi việc, mọi mong cầu đều tập hợp thành tựu.',
  'Minh Phệ Đối': 'Cát tinh. Tốt cho việc an táng.',
  'Minh Phệ': 'Cát tinh. Tốt cho việc an táng, dập tà.',
  'Bất Tương': 'Cát tinh. Rất tốt cho giá thú.',
  'Thiên Thương': 'Cát tinh. Tốt cầu tài lộc, mở kho, kinh doanh.',
  'Ngũ Phú': 'Cát tinh. Cầu phú quý trọn vẹn năm hướng.',
  'Trừ Thần': 'Cát tinh. Tốt cho dọn dẹp, trừ tà, bỏ đồ cũ.',
  'Yếu An': 'Cát tinh. Tốt cho việc cần yên tĩnh, an vị, trấn trạch.',
  'Ngọc Vũ': 'Cát tinh. Tốt cho xây dựng, tu tạo.',
  'Tiểu Hội': 'Cát tinh nhỏ. Tốt hội họp.',
  'Đại Hội': 'Cát tinh lớn. Tốt cho quần tụ tiệc tùng lớn.',
  'Phúc Hậu': 'Cát tinh. Tốt cho cầu phúc, tế tự lâu dài.',
  'U Vi Tinh': 'Kiết tinh nhỏ, bổ trợ.',

  // --- HUNG TINH & ĐẠI HUNG TINH ---
  'Thụ Tử': 'Đại hung tinh (sao Thụ Tử). Kỵ trăm việc, trăm sự đều hung, đặc biệt kỵ xuất hành, bệnh tật kéo dài khó qua.',
  'Sát Chủ': 'Đại hung tinh. Kỵ xây cất, cưới hỏi, an táng, làm gì cũng gặp chuyện không như ý, tai ương giáng xuống.',
  'Ngũ Hư': 'Hung tinh. Kỵ khởi công, giá thú, an táng. Làm việc dễ mất công vô ích, tiền bạc hao tổn, không có thực kết quả.',
  'Ngũ Phá': 'Hung tinh. Kỵ mọi việc. Dễ đổ vỡ, chia ly, tổn thất giữa chừng.',
  'Thiên Hình': 'Hắc đạo hung tinh. Kỵ kiện tụng, tranh chấp, dễ nguy cơ hình phạt, lao lý.',
  'Bạch Hổ': 'Hắc đạo hung tinh. Kỵ an táng, cưới hỏi, xuất hành, chủ về chết chóc, tai ương đẫm máu.',
  'Chu Tước': 'Hắc đạo hung tinh. Kỵ nhập trạch, khai trương, dễ sinh cự cãi, rắc rối giấy tờ miệng tiếng.',
  'Thiên Lao': 'Hắc đạo hung tinh. Kỵ mọi việc, nguy cơ tù tội, vướng mắc kiện cáo dai dẳng.',
  'Huyền Vũ': 'Hắc đạo hung tinh. Kỵ xuất hành, an táng, đề phòng mất trộm, hao tài, lừa đảo.',
  'Câu Trận': 'Hắc đạo hung tinh. Kỵ chôn cất, cưới xin, làm việc lớn có nhiều trở ngại.',
  'Đại Hao': 'Hung tinh. Kỵ mua tậu tài sản, xuất tiền phá của. Dễ mất mát tài sản lớn hao tài.',
  'Tiểu Hao': 'Hung tinh. Kỵ kinh doanh, lặt vặt tiêu tốn, hao mòn tài sản.',
  'Tử Thần': 'Đại hung tinh. Rất kỵ kiện tụng, chữa bệnh, xuất hành, chủ về hung hiểm đến tính mạng.',
  'Nguyệt Phá': 'Hung tinh. Ngày bạo tàn xung với tháng, không nên làm việc lớn, hung vạn sự.',
  'Kiếp Sát': 'Theo tuế sát. Kỵ xuất hành, giá thú, an táng. Dễ bị cướp giật, thương tích.',
  'Tai Sát': 'Theo tuế sát. Kỵ mọi việc. Dễ bị dịch bệnh, tai ương.',
  'Tuế Sát': 'Theo tuế sát. Kỵ thay đổi chỗ ở, tu tạo.',
  'Thiên Cẩu': 'Hung tinh. Kỵ tế tự, giá thú, cầu con, sinh đẻ. Dễ có tai ương, sẩy thai.',
  'Thiên Tặc': 'Đại hung tinh. Kỵ khởi tạo, xuất hành, phòng kẻ gian trộm cướp, mất của.',
  'Hỏa Tai': 'Đại hung tinh. Kỵ làm bếp, xây dựng, cất nóc. Dễ dẫn đến hỏa hoạn nhà cửa.',
  'Địa Hỏa': 'Hung tinh. Kỵ làm bếp, động thổ, trồng trọt, dễ gặp tai nạn do lửa.',
  'Thiên Hỏa': 'Hung tinh. Kỵ lợp nhà, làm bếp. Dễ xảy ra hỏa hoạn.',
  'Vãng Vong': 'Đại hung tinh. Kỵ việc xuất hành, đi xa, cưới hỏi, cầu tài, đi nhưng không quay về.',
  'Tứ Phế': 'Đại hung tinh. Ngũ hành tứ mùa tàn tạ, không có sinh khí (ngày tuyệt). Kỵ mọi việc lớn.',
  'Tiểu Hồng Sa': 'Hung tinh. Tránh làm các việc hỷ sự, quan trọng vạn sự khởi đầu nan.',
  'Địa Phá': 'Hung tinh. Kỵ việc xây dựng, động thổ.',
  'Hà Khôi': 'Hung tinh. Kỵ khởi công, xây dựng, tranh chấp.',
  'Du Họa': 'Hung tinh. Kỵ việc xây dựng, sửa chữa nhà cửa, tránh mạo hiểm.',
  'Thổ Ôn': 'Hung tinh. Kỵ xây dựng, động thổ, đào ao giếng.',
  'Cửu Không': 'Hung tinh. Kỵ việc xuất hành, cầu tài, mọi sự trống rỗng, không thành đạt.',
  'Trùng Nhật': 'Hung tinh. Kỵ việc an táng, làm việc dễ bị lặp lại 2 lần (sợ trùng tang).',
  'Phục Nhật': 'Hung tinh. Kỵ việc an táng.',
  'Cô Thần': 'Hung tinh. Kỵ việc cưới hỏi, giá thú. Nữ làm dễ cô độc quạnh hiu.',
  'Quả Tú': 'Hung tinh. Kỵ việc cưới hỏi, giá thú.',
  'Bát Chuyên': 'Hung tinh. Kỵ việc cưới hỏi, xuất hành.',
  'Âm Thác': 'Hung tinh. Kỵ xuất hành, cưới hỏi.',
  'Dương Thác': 'Hung tinh. Kỵ xuất hành, cưới hỏi.',
  'Băng Tiêu Ngoạ Hãm': 'Đại hung. Mọi việc dễ chóng tàn lụi, tiêu tan thành mây khói.',
  'Thiên Địa Chuyển Sát': 'Rất tồi tệ cho mọi việc, kỵ động thổ, khai trương.',
  'Lục Xà': 'Hung tinh. Mang tính xui xẻo, dòm ngó. Kỵ các việc mong may mắn.',
  'Đại Sát': 'Hung tinh cực mạnh. Kỵ mọi việc, đặc biệt xuất hành, cưới hỏi.',
  'Xúc Thủy Long': 'Hung tinh. Kỵ các việc liên quan tới nước, đi thuyền, cầu phà.',
  'Nguyệt Sát': 'Hung tinh. Kỵ mọi sự việc liên quan tới tài sản.',
  'Nguyệt Hư': 'Hung tinh. Kỵ mọi việc, dễ làm xong bị hư mất.',
  'Hạ Khuyển': 'Hung tinh. Kỵ xuất hành, cẩn trọng lời nói kẻo bị chửi rủa.',
  'Thần Cách': 'Hung tinh. Kỵ tế tự, cúng bái vì thần Phật bị cách trở không thấu.',
  'Nguyệt Hình': 'Hung tinh. Kỵ mọi việc do xung hình.',
  'Nguyệt Hại': 'Hung tinh. Kỵ mọi việc, dễ sinh cự cãi, hãm hại sau lưng.',
  'Địa Nang': 'Hung tinh. Kỵ xuất hành, đào móng.',
  'Thiên Cương': 'Quả Cương ác tinh. Sát khí nặng, kỵ làm đình đám, kinh tế lớn.',
  'Mộc Mã': 'Hung tinh. Dễ gặp gian cản.',
  'Thổ Phù': 'Hung tinh. Kỵ động thổ, xây dựng.',
  'Thổ Phủ': 'Hung tinh. Kỵ động thổ, nhập trạch.',
  'Đại Thời': 'Hung tinh. Xấu mọi việc.',
  'Tiểu Thời': 'Hung tinh nhỏ. Không tốt cho việc nhanh chóng.',
  'Hàm Trì': 'Hung tinh (còn gọi là sao Đào Hoa sát). Kỵ giá thú, cưới hỏi, dễ sinh chuyện phong lưu mờ ám, ngoại tình.',
  'Ngũ Ly': 'Hung tinh. Kỵ giá thú cưới hỏi. Chủ sự chia tay, ly tán.',
  'Nguyệt Yếm': 'Hung tinh. Kỵ cưới hỏi giá thú.',
  'Thiên Lại': 'Hung tinh. Kỵ tranh chấp, kiện tụng vì dễ thua thiệt.',
  'Địa Tặc': 'Hung tinh. Kỵ khởi tạo, coi chừng tiểu nhân, kẻ cắp từ bên trong.',
  'Phi Ma': 'Hung tinh. Kỵ an táng, cưới xin.',
  'Phi Liêm': 'Hung tinh. Kỵ đại quan, nhậm chức, dời chỗ ở.',
  'Thiên Ôn': 'Hung tinh. Kỵ việc lớn.',
  'Kiếp Thứ': 'Hung tinh. Kỵ tranh chấp, binh đao.',
  'Tam Tang': 'Đại hung tinh. Xấu nhất cho việc chôn cất, dễ bị trùng tang 3 người.',
  'Quỷ Khốc': 'Hung tinh thần sầu quỷ khóc. Kỵ tế tự, tang đạo.',
  'Quy Kỵ': 'Hung tinh. Kỵ các việc quay về, về nhà cũ, dọn vào nhà mới.',
  'Trí Tử': 'Đại hung tinh. Chủ gây ra sự tử vong. Kỵ chữa bệnh nguy hiểm, cầu y, cầu tự.',
  'Thời Âm': 'Hung tinh, ngăn chặn dương khí sinh trưởng.',
  'Tử Khí': 'Hung tinh. Kỵ việc sinh mang mầm sống.',
  'Yếm Đối': 'Hung tinh cản trở mọi bề.',
  'Chiêu Diêu': 'Hung tinh hay đi rải dối lừa, thị phi.',
  'Cửu Khảm': 'Hung tinh. Kỵ đi sông đi biển.',
  'Cửu Tiêu': 'Hung tinh cháy rụi.',
  'Đại Bại': 'Hung tinh. Kỵ mọi việc khởi sự, cầu tài.',
  'Tứ Kích': 'Hung tinh gây xích mích va chạm.',
  'Nguyên Vũ': 'Hắc đạo hung tinh.',
  'Bát Phong': 'Hung tinh. Kỵ đi mảng thuyền đi gió.',
  'Huyết Chi': 'Hung tinh. Kỵ châm cứu, trích lể, mổ xẻ.',
  'Huyết Kỵ': 'Hung tinh. Kỵ châm cứu, trích lể do xuất huyết.',
  'Trục Trận': 'Hung tinh kỵ ra trận, xuất hành quân sự.',
  'Tam Âm': 'Hung tinh u ám.',
  'Tứ Kỵ': 'Hung tinh tứ thời.',
  'Tứ Hao': 'Hung tinh gây hao phí cả 4 mùa.',
  'Bát Long': 'Hung tinh làm bế tắc công ăn.',
  'Tứ Cùng': 'Hung tinh tàn kiệt nguồn sống tiền bạc. Kỵ cầu tài.',
  'Ngũ Mộ': 'Hung tinh chôn vùi.',
  'Thất Điểu': 'Hung tinh nhỏ.',
  'Âm Dương Câu Thác': 'Hung tinh, mọi việc đảo lộn sai lệch.',
  'Âm Dương Kích Xung': 'Hung tinh, có sự va chạm mạnh bạo, tranh chấp.',
  'Cửu Hổ': 'Hung tinh, hiểm họa ập đến ngỡ ngàng.',
  'Âm Đạo Xung Dương': 'Hung tinh, khí xấu nổi lên.',
  'Thiên Phù': 'Hung tinh mang bùa chú rắc rối.',
  'Tuế Bạc': 'Hung tinh làm mỏng manh cơ nghiệp.',
  'Thuần Âm': 'Hung tinh sinh nấm mốc.',
  'Thuần Dương': 'Hung tinh nứt nẻ gãy đổ.',
  'Hành Ngoan': 'Hung tinh hay sinh sự ngang bướng cản trở.',
  'Hoang Vu': 'Hung tinh. Làm việc gì cũng bị bỏ dở, khó thành tựu.',
  'Bốc Mộc': 'Hung tinh.',
  'Giác Kỷ': 'Hung tinh.',
  'Lập Tảo': 'Hung tinh nhỏ.',
  'Ngột': 'Hung tinh.',
  'Thiết Xà': 'Hung rắn sắt, kỵ động chạm sửa chữa.',
  'Long Hổ': 'Hung tinh đầm rồng hang hổ, nguy cơ bất trắc.',
  'Tứ Thời Đại Mộ': 'Hung tinh. Kỵ khởi công, động thổ xây móng.',
  'Tứ Thời Cô Quả': 'Hung tinh. Kỵ giá thú, cưới hỏi 4 mùa.'
};

export const getStarMeaning = (starName: string): string => {
  if (STAR_MEANINGS[starName]) return STAR_MEANINGS[starName];
  if (['Thanh Long', 'Minh Đường', 'Kim Quỹ', 'Thiên Đức', 'Ngọc Đường', 'Tư Mệnh'].includes(starName)) {
    return 'Hoàng Đạo Kiết Tinh. Chòm sao chủ đạo cho sự phát đạt, thành công trong vạn sự.';
  }
  if (['Thiên Quan', 'Phúc Tinh', 'Hỷ Thần'].includes(starName)) {
    return 'Cát Tinh biểu hiện sự may mắn, phước lành, thăng tiến công danh.';
  }
  return 'Tính chất của sao này thuộc tập hợp các sao thứ cấp bổ trợ. Tùy thuộc vào Cát hay Hung tinh mà nó có ý nghĩa tăng thêm một chút may mắn hoặc một chút phiền toái. Bạn nên dựa vào các Đại Hung/Kiết Tinh trong ngày để quyết định.';
};
